tasks:
  - init: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
    command: |
      python manage.py runserver 0.0.0.0:8080
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - batisteo.vscode-django
